name: "cms_analytics"
version: "0.1.0"
config-version: 2

profile: "cms_analytics"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["dbt_tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

require-dbt-version: [">=1.10.0", "<1.12.0"]

models:
  cms_analytics:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: ephemeral
      +schema: intermediate
    marts:
      +materialized: table
      +schema: marts

seeds:
  cms_analytics:
    +schema: seeds
