"""Guard that `_cms__sources.yml` matches the registry projection.

The dbt sources file is generated by ``scripts/gen_cms_sources.py``
from ``libs/cms_api/datasets.toml``. A pre-commit hook regenerates it
on every commit, but editors and ``--no-verify`` can sneak a drift
past that — this test is the backstop. If it fails, the hint message
tells the contributor how to re-sync.
"""

from __future__ import annotations

import importlib.util
from pathlib import Path
import sys

from cms_api import load_registry


_REPO_ROOT = Path(__file__).resolve().parents[1]
_GENERATOR = _REPO_ROOT / "scripts" / "gen_cms_sources.py"
_SOURCES_YML = _REPO_ROOT / "dbt" / "cms_analytics" / "models" / "staging" / "cms" / "_cms__sources.yml"


def _load_generator() -> object:
    """Import ``scripts/gen_cms_sources.py`` without putting `scripts/` on sys.path."""
    spec = importlib.util.spec_from_file_location("gen_cms_sources", _GENERATOR)
    if spec is None or spec.loader is None:
        msg = f"Could not load module spec for {_GENERATOR}"
        raise RuntimeError(msg)
    module = importlib.util.module_from_spec(spec)
    sys.modules["gen_cms_sources"] = module
    spec.loader.exec_module(module)
    return module


def test_dbt_sources_yml_matches_registry() -> None:
    """Regenerate the YAML in memory and assert it matches the on-disk copy."""
    generator = _load_generator()
    expected = generator.render(load_registry())  # type: ignore[attr-defined]
    actual = _SOURCES_YML.read_text(encoding="utf-8")
    assert actual == expected, (
        f"{_SOURCES_YML.relative_to(_REPO_ROOT)} is out of sync with "
        "libs/cms_api/datasets.toml. Run:\n"
        "    uv run python scripts/gen_cms_sources.py --write\n"
        "to regenerate, then commit the result."
    )
